### ISSUE TITLE
missing ebuild or wrong manifest (gnome-weather)

### ISSUE THREAD

**Issue by aspann** [hhfeuer/Gentoo-Gnome-3.28-X#1]
Hi,
there is a small issue in gnome-weather. The manifest contains the non-existent ebuild "gnome-weather-3.26.2.ebuild".

[edit]:
In your Gentoo-Gnome-3.26-X repo is the same issue.

**Comment by hhfeuer** [comment]
Thanks for finding this, really odd. I've already pushed the changes.

**Comment by aspann** [comment]
Wow, 
what a quick response! 
I've closed my pull. everything seems fine now.

**Comment by hhfeuer** [comment]
Must have been a really strange bug in portage tools, the manifest was also missing the dist hash.
