### ISSUE TITLE
Missing dev-lang/vala-0.38.9 RDEPEND on media-gfx/graphviz

### ISSUE THREAD

**Issue by aspann** [hhfeuer/Gentoo-Gnome-3.28-X#11]
Hi,
sadly there is an issue located at dev-lang/vala. media-gfx/graphviz should be a RDEPEND because it was introduced in version 0.37.1.

Vala changelog (https://abi-laboratory.pro/index.php?view=changelog&l=vala&v=0.37.1):
> Vala 0.37.1
> ===========
> [...]
>   - [**#772426**] Merge valadoc - Consider valadoc a part of vala's toolchain and
>     therefore let it live in the main repository (adds graphviz to the
>     build-requirements)

should be fixed by: https://github.com/hhfeuer/Gentoo-Gnome-3.28-X/pull/10

**Comment by hhfeuer** [comment]
Thanks for finding this. Merged since docs are also not optional.
