### ISSUE TITLE
gnome-extra/gnome-system-monitor-3.28.2::Gnome-3-28-X failed to emerge

### ISSUE THREAD

**Issue by enx1998** [hhfeuer/Gentoo-Gnome-3.28-X#14]
Hi,
gnome-extra/gnome-system-monitor-3.28.2::Gnome-3-28-X fails to emerge with this error:

> /usr/bin/msgfmt --xml --template org.gnome.gnome-system-monitor.policy.in -d ./po -o org.gnome.gnome-system-monitor.policy
/usr/bin/msgfmt: cannot locate ITS rules for org.gnome.gnome-system-monitor.policy.in

Is there anything I can do to solve this issue?

Thanks Vincenzo

**Comment by hhfeuer** [comment]
I'm not 100% sure, but this sounds like polkit-0.114 not yet being installed. This has to be unmasked and keyworded.

**Comment by hhfeuer** [comment]
True. Is fixed now.
