### ISSUE TITLE
gnome-system-monitor-3.28.2 issue due upstream mask of sys-auth/polkit

### ISSUE THREAD

**Issue by aspann** [hhfeuer/Gentoo-Gnome-3.28-X#3]
Hi,
found another thing/enhancement.. sys-auth/polkit is masked in upstream (>0.114 by [set 2047](https://gentoobrowse.randomdan.homeip.net/packages/sys-auth/polkit#masks)) wich is needed by many gettext generations since gnome-3.26.

So maybe update your readme to unmask it. (currently tested with sys-auth/polkit-0.155)

[edit]:
Sorry, I over read it (you mention it)... but for some reason it didn't compile.. I had to unmask 0.155
I'll recheck it..

**Comment by aspann** [comment]
Okey, looked like my gentoo was trolling me...
Works with polkit-0.114!

**Comment by aspann** [comment]
sorry, I've to reopen this issue.. 

you mentioned it in the keywords, section - but is has to be unmask

**Comment by hhfeuer** [comment]
3.26 compiles with polkit-0.113, 3.28 needs 0.114.
It's mentioned that it needs an entry in package.unmask _and_ package.keywords/.accept_keywords

**Comment by aspann** [comment]
Ah, thanks for pointing that out.. :)
