### ISSUE TITLE
gnome-control-center-3.28.2 - compile error: missing krb5/krb5.h 

### ISSUE THREAD

**Issue by aspann** [hhfeuer/Gentoo-Gnome-3.28-X#5]
Hi,
I think gnome-control-center should depend on "app-crypt/mit-krb5"
(this issue cames up on a system wich uses heimdal instead of mit-krb5)

```
../gnome-control-center-3.28.2/panels/user-accounts/um-realm-manager.c:25:10: fatal error: krb5/krb5.h: No such file or directory    
 #include <krb5/krb5.h>
          ^~~~~~~~~~~~~
compilation terminated.
```

**Comment by hhfeuer** [comment]
That's probably the edge case where heimdall is installed but USE="-kerberos" is set. g-c-c uses autodetection for kerberos, sees heimdall, enables kerberos usage but really wants mit-krb5.
I'll come up with a patch for that.

**Comment by hhfeuer** [comment]
Added a patch to make kerberos optional and changed gnome-control-center-3.28.2.ebuild to properly honor the kerberos USE flag. Please check.

**Comment by aspann** [comment]
Hey,
yes, it was exacly that case you described. 
It's working now. (Fixed by: https://github.com/hhfeuer/Gentoo-Gnome-3.28-X/commit/e9df862de2bb738fb5de30f26a67ec3035481758)

Many thanks!
