### ISSUE TITLE
sys-auth/polkit needs to be keyworded

### ISSUE THREAD

**Issue by adimanav** [hhfeuer/Gentoo-Gnome-3.28-X#6]
sys-auth/polkit needs to be keyworded using ~amd64 as otherwise gnome-extra/gnome-system-monitor fails to emerge.

**Comment by hhfeuer** [comment]
Yes, and it also has to be unmasked. This is mentioned in the Quirks section. Please read.

**Comment by aspann** [comment]
I think this issue can be tagged as "wontfix" and closed. :)

@adimanav : look at my issue (https://github.com/hhfeuer/Gentoo-Gnome-3.28-X/issues/3), I did the same... (shame on me)

everyone can overread important things... 

@hhfeuer please close..

**Comment by hhfeuer** [comment]
I'm not 100% sure, but this sounds like polkit-0.114 not yet being installed. This has to be unmasked and keyworded.

**Comment by hhfeuer** [comment]
Closing this now since polkit-0.114 was removed from portage and replaced with polkit-0.115-r1 which now doesn't need to be unmasked anymore but still needs keyword ~amd64 set. Updated the README to reflect the new packages in portage.
