### ISSUE TITLE
Some apps crash with missing schema errors

### ISSUE THREAD

**Issue by mgiritli** [hhfeuer/Gentoo-Gnome-3.28-X#9]
The following programs (gnome-screenshot and gnome-photos) are failing to start with similar error messages:

gnome-screenshot 

(gnome-screenshot:10826): GLib-GIO-ERROR **: 09:55:23.402: Settings schema 'org.gnome.gnome-screenshot' is not installed

Trace/breakpoint trap (core dumped)
 ~ $ gnome-photos 

(org.gnome.Photos:10844): GLib-GIO-ERROR **: 09:55:35.413: Settings schema 'org.freedesktop.Tracker.Miner.Files' is not installed

Trace/breakpoint trap (core dumped)

**Comment by mgiritli** [comment]
add gnome-documents to that list:

$ gnome-documents 

(org.gnome.Documents:11689): GLib-GIO-ERROR **: 10:00:57.133: Settings schema 'org.freedesktop.Tracker.Miner.Files' is not installed

Trace/breakpoint trap (core dumped)

**Comment by hhfeuer** [comment]
tracker-miners is now added, the tracker ebuild is reworked and bumped. Did involve USE changes, changed gnome-extra-apps, gnome-photos, gnome-documents and gnome-music accordingly. Requires a --newuse --deep update. Please check.

**Comment by mgiritli** [comment]
Yes, they all seem to be working now, thank you.

**Comment by hhfeuer** [comment]
Thanks for reporting back. Closing.
